dataset:
  data_path: data/
  dev_ratio: 0.2
  file_name: nets_test.pkl
  has_node_feat: false
  is_overwrite_precompute: false
  is_sample_subgraph: false
  is_save_split: false
  loader_name: GRANData
  name: custom
  node_order: DFS
  num_fwd_pass: 1
  num_subgraph_batch: 1
  train_ratio: 0.8
device: cuda:0
exp_dir: exp/GRAN
exp_name: GRANMixtureBernoulli_custom_2020-May-21-10-21
gpus:
- 0
model:
  block_size: 1
  dimension_reduce: true
  edge_weight: 1.0
  embedding_dim: 128
  has_attention: true
  hidden_dim: 128
  is_sym: true
  max_num_nodes: 25
  name: GRANMixtureBernoulli
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  num_mix_component: 20
  sample_stride: 1
num_nodes_pmf: '[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1,
  0.125, 0.075, 0.0, 0.025, 0.125, 0.1, 0.025, 0.05, 0.05, 0.05, 0.075, 0.1]'
run_id: '404'
runner: GranRunner
save_dir: exp/GRAN/GRANMixtureBernoulli_custom_2020-May-21-10-21
seed: 1234
test:
  batch_size: 1
  better_vis: false
  is_single_plot: false
  is_test_ER: false
  is_vis: true
  num_test_gen: 20
  num_vis: 20
  num_workers: 0
  test_model_dir: config
  test_model_name: model_small.pth
  vis_num_row: 3
train:
  batch_size: 1
  display_iter: 10
  is_resume: false
  lr: 0.0001
  lr_decay: 0.1
  lr_decay_epoch:
  - 100000000
  max_epoch: 1000
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_dir: null
  resume_epoch: 5000
  resume_model: model_snapshot_0000500.pth
  shuffle: true
  snapshot_epoch: 1000
  valid_epoch: 50
  wd: 0.0
use_gpu: true
use_horovod: false
